import {saveRound, loadRounds} from './sync.js';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const phase2=true;
const prefix=phase2?'under360-phase2-239-v1-':'kruaprom-fresh-v1-',read=(k,f)=>{try{return JSON.parse(localStorage.getItem(prefix+k))??f;}catch{return f;}};
function write(k,v){try{localStorage.setItem(prefix+k,JSON.stringify(v));return true;}catch{toast('พื้นที่จัดเก็บไม่พร้อม กรุณาอย่าปิดหน้านี้');return false;}}
const unitOptions=['g','kg','ml','ลิตร','ชิ้น','ฟอง','ลูก','หัว','ต้น','ใบ','แผ่น','คู่','ถุง','แพ็ค','ขวด','กระป๋อง','กล่อง','ม้วน'];
const storedUnits=read('units',{});
const selectedUnits=storedUnits&&typeof storedUnits==='object'&&!Array.isArray(storedUnits)?storedUnits:{};
const unit=v=>({g:'กรัม',kg:'กก.'}[v]||v||'ยังไม่เลือกหน่วย'),step=v=>v==='g'?100:v==='kg'?.1:1,fmt=v=>Number(v).toLocaleString('th-TH',{maximumFractionDigits:3});
let items=[],values=read('draft',{}),rounds=read('rounds',[]),custom=read('items',[]),recent=[],filter='all',page=0;const size=30;
if(!values||Array.isArray(values)||typeof values!=='object')values={};if(!Array.isArray(rounds))rounds=[];if(!Array.isArray(custom))custom=[];
const counted=i=>(!phase2||!!items.find(x=>x.key===i.key)?.unit)&&Object.hasOwn(values,i.key)&&Number.isFinite(values[i.key])&&values[i.key]>=0;
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,4200);}
function update(){const done=items.filter(counted),zero=done.filter(i=>values[i.key]===0).length;$('heroDone').textContent=done.length;$('heroTotal').textContent=items.length;$('allN').textContent=items.length;$('pendingN').textContent=items.length-done.length;$('doneN').textContent=done.length;$('countN').innerHTML=done.length+' <small>รายการ</small>';$('remain').textContent='จากทั้งหมด '+items.length+' รายการ';$('progress').max=items.length||1;$('progress').value=done.length;$('hasN').textContent=done.length-zero;$('zeroN').textContent=zero;$('mobileN').textContent=done.length?'นับแล้ว '+done.length+' / '+items.length:'ยังไม่เริ่มนับ';document.querySelectorAll('.finish').forEach(b=>{b.disabled=!done.length||!!document.querySelector('.counter input:invalid');b.innerHTML='ตรวจสอบ '+done.length+' รายการ <span>→</span>';});$('recent').innerHTML=recent.filter(k=>counted({key:k})).slice(0,4).map(k=>{const i=items.find(x=>x.key===k);return i?`<div class="recent-row"><span>${esc(i.name)}</span><b>${fmt(values[k])} ${unit(i.unit)}</b></div>`:'';}).join('')||'<p>รายการที่นับจะแสดงที่นี่</p>';}
function row(i){const done=counted(i);return `<article class="product ${done?'done':''}" data-key="${esc(i.key)}"><div class="photo">${i.img?`<img src="${esc(i.img)}" alt="${esc(i.name)}" loading="lazy" decoding="async" width="160" height="160">`:'<span class="no-photo">ยังไม่มีรูป</span>'}</div><div class="product-info"><h3>${esc(i.name)}</h3><div class="meta">${esc(unit(i.unit))}</div></div><div class="entry"><div class="counter"><button ${phase2&&!i.unit?'disabled':''} data-step="-1" aria-label="ลดจำนวน ${esc(i.name)}">−</button><input ${phase2&&!i.unit?'disabled':''} aria-label="จำนวน ${esc(i.name)}" type="number" min="0" step="any" inputmode="decimal" placeholder="แตะเพื่อกรอก" value="${done?values[i.key]:''}"><button ${phase2&&!i.unit?'disabled':''} data-step="1" aria-label="เพิ่มจำนวน ${esc(i.name)}">+</button></div><div class="counter-meta"><button class="clear" data-clear aria-label="ล้างจำนวน ${esc(i.name)}">ล้าง</button></div></div><span class="check" aria-label="นับแล้ว">✓</span></article>`;}

function render(){const q=$('query').value.trim().toLocaleLowerCase(),cat=$('category').value;const list=items.filter(i=>(cat==='all'||i.group===cat)&&(!q||i.name.toLocaleLowerCase().includes(q))&&(filter==='all'||filter==='done'&&counted(i)||filter==='pending'&&!counted(i)));const pages=Math.ceil(list.length/size);page=Math.max(0,Math.min(page,pages-1));$('products').innerHTML=list.slice(page*size,(page+1)*size).map(row).join('')||'<p class="empty">ไม่พบรายการ ลองเปลี่ยนคำค้นหรือหมวด</p>';$('products').querySelectorAll('img').forEach(img=>img.onerror=()=>{const i=items.find(x=>x.key===img.closest('.product').dataset.key);img.parentElement.innerHTML='<span class="no-photo">ยังไม่มีรูป</span>';});$('pages').hidden=pages<=1;$('pages').innerHTML=`<button data-page="${page-1}" ${!page?'disabled':''} aria-label="หน้าก่อนหน้า">‹</button><span>${page*size+1}–${Math.min((page+1)*size,list.length)} จาก ${list.length} รายการ</span><button data-page="${page+1}" ${page>=pages-1?'disabled':''} aria-label="หน้าถัดไป">›</button>`;update();}
function persist(key){recent=[key,...recent.filter(k=>k!==key)];write('draft',values);const el=[...$('products').children].find(a=>a.dataset.key===key);if(el){const done=counted({key});el.classList.toggle('done',done);const meta=el.querySelector('.meta');meta.classList.toggle('done-label',done);if(!phase2)meta.textContent=unit(items.find(i=>i.key===key).unit);else meta.textContent=unit(items.find(i=>i.key===key).unit);}update();}
$('products').addEventListener('input',e=>{if(!e.target.matches('input'))return;const input=e.target,k=input.closest('.product').dataset.key;if(input.validity.badInput||input.value!==''&&(!Number.isFinite(Number(input.value))||Number(input.value)<0)){input.setCustomValidity('กรอกจำนวนตั้งแต่ 0 ขึ้นไป');update();return;}input.setCustomValidity('');if(input.value==='')delete values[k];else values[k]=Number(input.value);persist(k);});
$('products').addEventListener('click',e=>{const b=e.target.closest('button'),a=b?.closest('.product');if(!a||b.disabled)return;const k=a.dataset.key,i=items.find(x=>x.key===k),input=a.querySelector('input');if(b.hasAttribute('data-clear'))delete values[k];else values[k]=Math.max(0,Math.round(((values[k]||0)+Number(b.dataset.step)*step(i.unit))*1000)/1000);input.value=values[k]??'';input.setCustomValidity('');persist(k);});
$('products').addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('input'))e.target.blur();});
function resetPage(){page=0;render();}$('query').oninput=resetPage;$('category').onchange=resetPage;document.querySelector('.filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('selected',x===b));resetPage();};$('pages').onclick=e=>{const b=e.target.closest('[data-page]');if(!b||b.disabled)return;page=Number(b.dataset.page);render();document.querySelector('.tools').scrollIntoView({block:'start'});};
function show(view){$('countView').hidden=view!=='count';$('historyView').hidden=view!=='history';$('footer').hidden=view!=='count';$('countNav').classList.toggle('active',view==='count');$('historyNav').classList.toggle('active',view==='history');$('crumb').textContent=view==='count'?'นับสต็อก':'รอบที่ผ่านมา';if(view==='history'){renderHistory();syncRounds();}}
$('countNav').onclick=()=>show('count');$('historyNav').onclick=()=>show('history');
const reviewRow=i=>`<div class="review-row"><span>${esc(i.name)}</span><b>${fmt(i.qty)} ${unit(i.unit)}</b></div>`;
document.querySelectorAll('.finish').forEach(b=>b.onclick=()=>{const invalid=document.querySelector('.counter input:invalid');if(invalid){invalid.reportValidity();return;}const done=items.filter(counted);$('reviewTotal').textContent='นับแล้ว '+done.length+' รายการ · ยังไม่ได้นับ '+(items.length-done.length);$('reviewRows').innerHTML=done.map(i=>reviewRow({...i,qty:values[i.key]})).join('');$('who').value=read('who','');$('review').showModal();});
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('finishForm').onsubmit=e=>{e.preventDefault();const who=$('who').value.trim();if(!who){$('who').setCustomValidity('กรุณาระบุชื่อ');$('who').reportValidity();return;}const done=items.filter(counted);if(!done.length)return;const r={id:crypto.randomUUID(),at:new Date().toISOString(),by:who,note:$('note').value.trim(),dataset:phase2?'phase2-239':'legacy-91',items:done.map(i=>({key:i.key,name:i.name,unit:i.unit,qty:values[i.key]}))};r.sync='pending';if(!write('rounds',[r,...rounds]))return;rounds.unshift(r);write('who',who);values={};recent=[];write('draft',values);$('note').value='';$('review').close();render();show('history');toast('เก็บรอบในเครื่องแล้ว กำลังส่งเข้าระบบ');syncRounds();};$('who').oninput=()=>$('who').setCustomValidity('');
function renderHistory(){let old=[];if(phase2){try{old=JSON.parse(localStorage.getItem('kruaprom-fresh-v1-rounds'))||[];}catch{} }const historyRounds=[...rounds,...old.map(r=>({...r,legacy:true}))];$('history').innerHTML=historyRounds.length?historyRounds.map((r,n)=>`<details class="history-round" ${n===0?'open':''}><summary><div><h2>${esc(new Date(r.at).toLocaleString('th-TH',{timeZone:'Asia/Bangkok',dateStyle:'medium',timeStyle:'short'}))}</h2><p>${r.legacy?'รายการเดิม · ':''}ตรวจนับโดย ${esc(r.by)} · ${r.sync==='synced'?'บันทึกส่วนกลางแล้ว':r.sync==='pending'?'รอส่งเข้าระบบ':'เก็บในเครื่อง'}</p></div><b>${r.items.length} รายการ　⌄</b></summary><div class="history-content">${r.note?`<p>${esc(r.note)}</p>`:''}${r.items.map(reviewRow).join('')}</div></details>`).join(''):'<div class="history-round empty">ยังไม่มีรอบที่เสร็จแล้ว<br>เริ่มนับสต็อก แล้วกดตรวจและจบรอบ</div>';}
$('add').onclick=()=>$('addDialog').showModal();$('addForm').onsubmit=e=>{e.preventDefault();const name=$('itemName').value.trim();if(!name)return;const i={key:'custom-'+crypto.randomUUID(),name,unit:$('itemUnit').value,group:'รายการของฉัน',emoji:'📦'};if(!write('items',[...custom,i]))return;custom.push(i);items.push(i);fillCategories();$('category').value='รายการของฉัน';$('query').value='';filter='all';document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('selected',b.dataset.filter==='all'));$('addDialog').close();$('addForm').reset();resetPage();toast('เพิ่ม '+name+' แล้ว');};
function fillCategories(){const current=$('category').value;$('category').innerHTML='<option value="all">ทุกหมวด</option>'+[...new Set(items.map(i=>i.group))].map(g=>`<option value="${esc(g)}">${esc(g)}</option>`).join('');$('category').value=current||'all';$('categoryTabs').innerHTML=[['all','ทั้งหมด'],...[...new Set(items.map(i=>i.group))].map(g=>[g,g])].map(([v,l])=>`<button data-category="${esc(v)}" class="${v===$('category').value?'selected':''}">${esc(l)}</button>`).join('');}
document.addEventListener('keydown',e=>{if(e.key==='/'&&!e.target.matches('input,textarea,select')&&!document.querySelector('dialog[open]')){e.preventDefault();show('count');$('query').focus();}});
async function init(){const date=new Date().toLocaleDateString('th-TH',{timeZone:'Asia/Bangkok',day:'numeric',month:'long',year:'numeric'});$('date').textContent=date;$('shortDate').textContent=date;try{const res=await fetch('/pwa/ing_assets/catalogue.json');if(!res.ok)throw Error();const data=await res.json();items=data.groups.flatMap(g=>g.items.map(i=>({...i,unit:phase2?(unitOptions.includes(selectedUnits[i.key])?selectedUnits[i.key]:'g'):i.unit,group:g.name,emoji:g.emoji}))).concat(phase2?[]:custom);values=Object.fromEntries(Object.entries(values).filter(([k,v])=>items.some(i=>i.key===k)&&Number.isFinite(v)&&v>=0));fillCategories();render();}catch{$('products').innerHTML='<p class="empty">โหลดรายการไม่ได้ กรุณารีเฟรชหน้าอีกครั้ง</p>';}}init();

$('categoryTabs').onclick=e=>{const b=e.target.closest('[data-category]');if(!b)return;$('category').value=b.dataset.category;fillCategories();resetPage();};

const notice=document.createElement('div');notice.className='phase-notice';notice.innerHTML='กรอกจำนวนได้เลย<br><small>หน่วยเริ่มต้น: กรัม · เว้นว่าง = ยังไม่นับ · 0 = ของหมด</small> <a href="/staff/v2/home">กลับหน้าทีม</a>';document.querySelector('.heading').after(notice);

let syncing=false;
async function syncRounds(){
 if(syncing)return;syncing=true;$('syncRetry').disabled=true;
 $('syncStatus').textContent='กำลังเชื่อมต่อฐานข้อมูลกลาง…';
 try{
  for(const r of rounds.filter(r=>r.sync==='pending')){
   await saveRound(r);
   r.sync='synced';write('rounds',rounds);
  }
  const remote=await loadRounds();
  const merged=new Map(rounds.map(r=>[r.id,r]));
  for(const r of remote)merged.set(r.id,{...r,sync:'synced'});
  rounds=[...merged.values()].sort((a,b)=>b.at.localeCompare(a.at));
  write('rounds',rounds);renderHistory();
  $('syncStatus').textContent='อัปเดตประวัติจากส่วนกลางแล้ว';
 }catch(e){
  $('syncStatus').textContent='เชื่อมต่อส่วนกลางไม่สำเร็จ รอบที่ยังไม่ส่งเก็บในเครื่องนี้แล้ว กดส่งซ้ำได้';
  renderHistory();
 }finally{syncing=false;$('syncRetry').disabled=false;}
}
$('syncRetry').onclick=syncRounds;
window.addEventListener('online',syncRounds);
syncRounds();
